### ISSUE TITLE
rename sets.json

### ISSUE THREAD

**Issue by Malapris** [MNeMoNiCuZ/sd-webui-thumbnailizer#2]
FileNotFoundError: [Errno 2] No such file or directory: 'V:\\_AI\\_GEN\\A1111_DATA\\extensions\\sd-webui-thumbnailizer\\scripts\\sets_template.json'

instead of sets.json

**Comment by MNeMoNiCuZ** [comment]
Thanks for the report.
Should be fixed now. If not you can manually rename sets.json to sets_template.json
