### ISSUE TITLE
No thumbnails

### ISSUE THREAD

**Issue by Kaneda56** [MNeMoNiCuZ/sd-webui-thumbnailizer#4]
After generating the thumbnails I restarted Stable Diffusion but it marks me for all checkpoints "thumbnail missing". The generated thumbnails are named "00027-dreamshaper_8.environment.png"

thanks

**Comment by MNeMoNiCuZ** [comment]
Did you switch back to the "Environment" thumbnail set in the Thumbnailizer tab?

The thumbnails generated with anything except "Default", will only show up in the thumbnailizer tab.

If you want to replace default thumbnails for other parts of A1111 UI, you have to edit the "Default" set and generate with that.

**Comment by Kaneda56** [comment]
![Capture4](https://github.com/MNeMoNiCuZ/sd-webui-thumbnailizer/assets/12573241/2dd431bb-9f22-4a83-8060-eec3ba6120c0)
Yes I am in the Thumbnailizer tab

**Comment by Kaneda56** [comment]
Is the number at the beginning of the filename normal? Shouldn't we have "dreamshaper_8.environment.png" instead of "00027-dreamshaper_8.environment.png"?

**Comment by MNeMoNiCuZ** [comment]
You are correct, the number shouldn't be there. I assumed your model was named 00027-dreamshaper_8 initially.
I'm not sure why it's added.

Can you please look at your regular A1111 settings:
![image](https://github.com/MNeMoNiCuZ/sd-webui-thumbnailizer/assets/60541708/55e3ce12-bf48-42c7-80a8-417370c15755)

Under Saving Images > Saving Images/Grids

There's a setting for: "Add Number to Filename when saving".
Do you have this enabled? It sounds like it's something like this.

My setting is off.
If yours is on, can you please try turning it off, saving, and then restarting completely and try again.

You can set the "Last Index" to 2, so it only generates for 3 checkpoints to test it out.

Thanks for your help.

**Comment by Kaneda56** [comment]
Yes ! It's fixed now. Thanks !
